name: FULLVISIONTRAINING
favicon: null
layout_spectrum: 0.3493138544727117
typography_spectrum: 0.15211350261233747
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.4520705824252218
  lightness: 0.6274751059245318
  saturation: 0.44314713729545474
  rhythmicContrast: 0.09053841512650251
purpose: []
